# users.nix
{
  config,
  inputs,
  pkgs,
  ...
}:

{
  users.users.eeshta = {
    isNormalUser = true;
    hashedPasswordFile = config.sops.secrets."users/password/eeshta".path;
    description = "eeshta";
    shell = pkgs.zsh;
    ignoreShellProgramCheck = true;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILSkZhHC1jkM6y4CO7tES6lLIADXbtoMUsyNJX66WreR miyu@mellowchan"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/p32VpwAw0X96/ih6L2EXHRr7oC2wlhTIy9kIfVDKG Generated By Termius"
    ];
    extraGroups = [ "wheel" ];
    packages = with pkgs; [
      protonup-qt
      obsidian
      zoom-us
      parsec-bin
      bitwarden-desktop

      wineWow64Packages.waylandFull
      winetricks

      # Minecraftのヤツ
      # temurin-jre-bin
      # temurin-jre-bin-17

      (prismlauncher.override {
        jdks = [
          temurin-jre-bin-8
          temurin-jre-bin-17
          temurin-jre-bin
        ];
      })

      # 作業系など
      unityhub
      vrc-get
      gimp3
      inputs.blender-bin.packages.x86_64-linux.blender_4_1
    ];
  };

  programs = {
    sleepy-launcher.enable = true;

    # Thunar組
    thunar.enable = true;
    xfconf.enable = true;

    # Mozilla組
    firefox.enable = true;
    thunderbird.enable = true;
  };
}
