# users.nix
{ config, lib, pkgs, inputs, ... }:

{
  users.users.eeshta = {
    isNormalUser = true;
    hashedPassword = "***REMOVED***";
    description = "eeshta";
    shell = pkgs.fish;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHh60Pl9Y6ns/1cNY6kZC4AF/M1yXwbWL3OibsRSdp6X NixOS"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/p32VpwAw0X96/ih6L2EXHRr7oC2wlhTIy9kIfVDKG Generated By Termius"
    ];
    extraGroups = [ "wheel" ];
    packages = with pkgs; [
      # 生活必需品
      protonup-qt
      vesktop
      obsidian
      zoom-us
      parsec-bin
      bitwarden-desktop

      # ゆーてぃりてぃ
      unzip unrar gh htop tmux

      # 主に東方向け
      wineWowPackages.waylandFull
      winetricks

      # Minecraftのヤツ
      # temurin-jre-bin
      # temurin-jre-bin-17

      (prismlauncher.override {
        jdks = [
          temurin-jre-bin-8 temurin-jre-bin-17 temurin-jre-bin
        ];
      })

      # 作業系など
      unityhub vrc-get gimp3
      inputs.blender-bin.packages.x86_64-linux.blender_4_1
    ];
  };

  programs = {
    # Thunar組
    thunar.enable = true;
    xfconf.enable = true;

    # Mozilla組
    firefox.enable = true;
    thunderbird.enable = true;
  };
}
